### ISSUE TITLE
Incident: API down

### ISSUE THREAD

**Issue by nalinbhardwaj** [daimo-eth/daimo#683]
## Summary

**Daimo API was down for 4h on Feb 8**. It appears to be triggered by (intermittently) very slow postgres queries due to an issue in Render, which revealed bugs in our indexing system. What caused the slowness is unclear, but Render's own site was also partly down during this time, showing intermittent 404 pages.

<img width="500" alt="image" src="https://github.com/daimo-eth/daimo/assets/169280/0cb6de31-1e4f-4e8e-9724-c9c4ba13653e">

## Timeline

**2024-02-08 Pacific time**

- **11:11am** - [payment link create transaction](https://basescan.org/tx/0x97168deec27612e11a369e423088a487457a452a2256cc7b66b940f9cd494463)
- **11:11** - server down
- **12:00** - attempted hotfix. deploy fails due to query read timeouts. potentially unrelated bug.
- **12:20** - investigating
- **12:45** - try reducing batch size https://github.com/daimo-eth/daimo/pull/686/commits/2567f9790590d556091ebd7bb53bc43b62cf9500
- **13:00** - the error from #624 reoccurs. issue revealed by smaller batch size. fixing. 
- **13:55** - fix notelog ordering #686 , deploy. https://github.com/daimo-eth/daimo/pull/686/commits/383151814586813e7993fe3d9285f7e7fae3f008
- **14:00** - still getting 10s query timeouts during api server startup.
- **~14:30** - upgraded postgres to larger instance, per Ryan Smith's recommendation.
- **~14:45** - upgraded app server to larger instance, based on Nalin's observation that memory use was high > we're possibly limited by node-pg trying to use disk.
- **15:15** - hotfix: api: 20s query timeout, simplify transfers query https://github.com/daimo-eth/daimo/pull/686/commits/8a70b5542f30fc9f7af67bfc2ce05e088f0725da
- **~15:30** - **still failing due to intermittent 60s (!) postgres queries. we see lots of 404s in the render webapp.** intermittent-- 404s typically go away on refresh. at this point, we're pretty sure there's a render issue, potentially a networking issue between our app server and db server.
- **15:59** - hotfix: retry with exponential backoff for queries. https://github.com/daimo-eth/daimo/commit/d2e26436c4cf1e117a3be37c0d33334e5d7ffaa1
- **16:09** - **back up, api healthy**

### Query timeout

**Issue appeared once, a week ago, and solved itself via auto restart.** Followup at the time: #667 

Today, appears again.

**during server startup > loading batches of ~100k blocks = ~100k transfers used to be fast, now hitting 10 second query timeout.**

https://logs.betterstack.com/team/183561/tail?q=&s=304118&a=1707420352844880.51000974

https://logs.betterstack.com/team/183561/tail?rf=1707410804492000&a=1707421604090943-56004139 transfers read is timing out.

### NoteCreated issue
Tx: https://basescan.org/tx/0x97168deec27612e11a369e423088a487457a452a2256cc7b66b940f9cd494463

Error log:
```
Error: bad NoteCreated: 0x6790974E8d7cbF5Caac517b97F84F53a226bCFfC exists
```

but there's only one of these in the DB?

<img width="1112" alt="Screenshot 2024-02-08 at 11 37 01 AM" src="https://github.com/daimo-eth/daimo/assets/6984346/660306f1-a612-46d6-8c91-ade28e07fed8">

**Separately, app server memory looks high.** 
![image](https://github.com/daimo-eth/daimo/assets/169280/2dbdbb15-6b25-4c77-a375-db249079df1a)

#### Links 404ing inside the render UI
![image](https://github.com/daimo-eth/daimo/assets/169280/508366e5-3e85-429d-8ea3-35de94dea225)

#### Render SSH dropping connections

per @nalinbhardwaj 

## Follow ups

- [x] query timeout - **fixed by adding retry + backoff**, #686
- [x] `error not ready` during startup makes it hard to search logs - #686
- [x] notecreated bug - #686 
- [x] add monitoring - **added UptimeRobot**
- [ ] **migrate from Render to AWS** https://github.com/daimo-eth/daimo/issues/687

**Comment by dcposch** [comment]
Follow up: #687 #664
